version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    command: [
      "--replSet", "rs0",
      "--bind_ip_all",
      "--setParameter", "enableTestCommands=1",
      "--setParameter", "defaultRWConcern={readConcernLevel: \"local\"}",
      "--setParameter", "replicationCoordinator.enableMajorityReadConcern=false"
    ]
    volumes:
      - mongodb_data:/data/db
    networks:
      - trunk_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand(\"ping\").ok'"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./examples/talkgroups.csv:/app/talkgroups.csv
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0&directConnection=true
      - DB_NAME=trunk_recorder
      - COLLECTION_NAME=radio_events
      - TALKGROUP_FILE=/app/talkgroups.csv
    depends_on:
      - mongodb
    networks:
      - trunk_network

  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0&directConnection=true
      - DB_NAME=trunk_recorder
      - COLLECTION_NAME=radio_events
      - HTTP_MONGO_PORT=3001
    depends_on:
      - mongodb
    networks:
      - trunk_network

  # Initialize MongoDB Replica Set
  mongo-init:
    image: mongo:latest
    restart: "no"
    depends_on:
      - mongodb
    command: >
      bash -c "
        echo 'Waiting for MongoDB to start...' &&
        until mongosh --host mongodb:27017 --eval 'db.runCommand(\"ping\").ok' >/dev/null 2>&1; do
          echo 'Waiting for MongoDB to be ready...'
          sleep 2
        done &&
        echo 'MongoDB is ready, initializing replica set...' &&
        mongosh --host mongodb:27017 --eval '
          config = {
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongodb:27017\", priority: 1 }
            ],
            settings: {
              chainingAllowed: true,
              heartbeatTimeoutSecs: 10,
              electionTimeoutMillis: 10000,
              catchUpTimeoutMillis: -1
            }
          };
          rs.initiate(config);
        ' &&
        echo 'Waiting for replica set to be ready...' &&
        until mongosh --host mongodb:27017 --eval 'rs.status().ok && rs.status().members.length > 0 && rs.status().members[0].stateStr === \"PRIMARY\"' >/dev/null 2>&1; do
          echo 'Waiting for replica set to be ready...'
          sleep 2
        done &&
        echo 'Replica set is ready and PRIMARY'
      "
    networks:
      - trunk_network

networks:
  trunk_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
