FROM node:20-slim

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy ingest service
COPY mqtt-mongo-service.js ./

CMD ["node", "mqtt-mongo-service.js"]
